// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pi_ETicaret_Sitesi.Contexts;

namespace Pi_ETicaret_Sitesi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201231082133_yorum2")]
    partial class yorum2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

           

            modelBuilder.Entity("Pi_ETicaret_Sitesi.Models.Yorum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Yorumlar");
                });

            
#pragma warning restore 612, 618
        }
    }
}
